apiVersion: batch/v1
kind: Job
metadata:
  name: aws-security-job
  namespace: defectdojo
spec:
  template:
    spec:
      containers:
        - name: aws-security
          image: anasbinaqeel/aws-security:1.0
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "<your-aws-access-key>"
            - name: AWS_SECRET_ACCESS_KEY
              value: "<your-aws-secret-key>"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: DEFECTDOJO_API_KEY
              value: "<your-defectdojo-api-key>"
      restartPolicy: Never
