apiVersion: apps/v1
kind: Deployment
metadata:
  name: bearer-service
  namespace: defectdojo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bearer-service
  template:
    metadata:
      labels:
        app: bearer-service
    spec:
      containers:
        - name: bearer
          image: your-dockerhub-username/bearer-microservice:1.0
          env:
            - name: TARGET
              value: "/some/code"
            - name: DEFECTDOJO_URL
              value: "http://10.102.74.156:30080" # Adjust based on DefectDojo service
            - name: DEFECTDOJO_API_KEY
              value: "your-api-key"
