apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobsf-service
  template:
    metadata:
      labels:
        app: mobsf-service
    spec:
      containers:
        - name: mobsf
          image: opensecurity/mobile-security-framework-mobsf:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mobsf-service
spec:
  selector:
    app: mobsf-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
