apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuclei-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuclei-service
  template:
    metadata:
      labels:
        app: nuclei-service
    spec:
      containers:
        - name: nuclei
          image: anasbinaqeel/nuclei-microservice:1.0
          env:
            - name: TARGET
              value: "http://example.com" # Or any domain you want to test
---
apiVersion: v1
kind: Service
metadata:
  name: nuclei-service
spec:
  selector:
    app: nuclei-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
