apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: defectdojo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: defectdojo-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: defectdojo-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: defectdojo
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: ssl-cert
              mountPath: /certs
          args:
            - "-c"
            - "ssl=on"
            - "-c"
            - "ssl_cert_file=/certs/server.crt"
            - "-c"
            - "ssl_key_file=/certs/server.key"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: ssl-cert
          secret:
            secretName: postgres-ssl-cert
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: defectdojo
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ssl-cert
  namespace: defectdojo
type: Opaque
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZDVENDQXZHZ0F3SUJBZ0lVUDVHMkFjKzRUamdRUnlnMUtJRVVPZ2N3ajFvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNQjRYRFRJMU1ERXhNVEUwTXpVeU9Gb1hEVEkyTURFeApNVEUwTXpVeU9Gb3dGREVTTUJBR0ExVUVBd3dKYkc5allXeG9iM04wTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBZzhBTUlJQ0NnS0NBZ0VBdERkL1BUdHo2SVd1RC9GSXcwWmdrL3BOenJqQ05mTUN0RWE2eHFoOExOU3IKVlNHYjR3QTkreTB5YU5iRktZc2JCb0RHY1hxRVNwWWtzSXdjNkRpTDlYakszYU9mT1FraURlNGJsM3psTmdNZApzZlluZGdORjkxZTRQcnpDZkYvMVBCZFFpNFhnM2FkQUdFejdsNmoyclJYelRXVVJwZTF0cXNUdHhkWTZLaC8vCmU5VEY3QXZOL1BsSFFHWFA1ZDZBQ0hJTXc2NHIyU1B3aUQyMkkrbnA2RW9PUHM5N01Va3VUVm80SVI1RTVxYnkKeGNnMTY2UWtrdnhJMGhNcFhBb1RSTk1XR3NCbGhyK1VHb0huSjkvVkhIWHpENWcyczB5L1BEekhhVXdZbm1nMgpaZllWSnNUS25NSGFHeGg3eFVpd2NnV3RFK2ZTVkxOaUI1T3lua1JPQ2V0MlQzM1MwT2o5Q0JyalFib1h0bGRiCjBFSHhVRmUrQXhNV2NFT0xkY2FFUXNDbUNqUm10NDlDRk1DUDVhV0dwQ1pEUmk2d1ArdEZEVmwvaWUrRkM1T3cKZnlzaHJ5ZzliNGJIcnhFZ1ZyNjRBT2hEb0lHdEh6dVVMZjhRMmdUaUhUYzk3SDg4N3VtejZXQ01QQkxRSC95Uwp3Z0ZxV0l6bEwrajlEMkdvRHg4TlhQK0NQL2RINmZhQWhJdEk0NWFFMTY2Q1oyTXFpRzhIejZZQ1BpbytKMng2CnZwaWZpZUpnWSszaWYwamtRZ1BENmZ6K3c3RjBSNlZ1N1hZcmJnZnlCbFNGZndQbS85SkZYdW9sZkxGb1lLWG0KaWtPcHFrRzlwdC84bDBVUCs1UFZsY0JvaGRmREdHTU9ZeXo5R3FkZmxCb3EwVjcxZGplbnlVejZLWjBjZWU4QwpBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGUHZxcHFmWkJZd1grVlJ0SDErcDJReWhVOTRHTUI4R0ExVWRJd1FZCk1CYUFGUHZxcHFmWkJZd1grVlJ0SDErcDJReWhVOTRHTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dJQkFCWXUzTW5aUzJMbXVXbVlPaFVxMHBWcTEwaGJ6WWsvcGhQaVpSMmZ6VnhEZlFmSgorckllRHdMSzBKbWJ0Z3lzcmxHL0xvWHM3ejJiVVJrVGJhbGo2UkRKc0FGenU4WFZlT0ZES2Fack1vejZLcmpsCmFvWXdwUDdsNjluWTFLcnlhWnR0M3pDVkkxL0F4a1FpeVBlU2NMSHBBRHhoaUM1UHBPTGNrQXk5MkgvcUFIODYKZHdVYmw2djlyc0NMbnMyZVBHMVltVml0L1NiazZFRlpUT1k0ZHVReUNHQTVMM1QzM3c5S2tNeGFYVHZyR3pNTQpOOUlXV29XN3IraXZaT1VCQ29aUWhOb1ZQTGRMVmZSMWcxNEpNR0dsM1NsT2ViN1liaFFpc283M0Z1eFhkT1hvCk1ENjJJMHYyRTNqOTl5azdicEM5REFiR2hVM3JMaW5MOVBicTVWeWpoNVJkNFFoS3gvOTM1ZjNtUXpsSlducm8KSVdjTCt6dWdKS3Mxa2wyQUhlbk5FZkxGR3pWM2w2b0R5WFFSTmkwU2laM09iWGJlNG1iM0dBM3A4MjlBTVoyNAp3Rm5mWlhMTjJtM1JObS9qK1pxMDNRQU50YjhuaGZpdTdSV3dUb0p1TnUrWlpmUW1PNitOMWN4UEFJOVJRbWp2CkZ1clNEclQ5MnpmZ3ozcndMVHZhZ0hWWitkaFpjMUloL3dxT2t3RXhIenpBK0xYUnFkbE1JQzh2ckhkZFMxM2MKemZOWTluN0Q2L1BXejdGRmNUZHZreVcvUnRFT0hkSlVMZ2ZqYmdJeWFyWm1OVXl2eEV5d2V2YnVIMU93SGhMMgp0MGVxZlVqME93TEpKSWlUU0hnaWVmWFh0T3poMXRYWTgvVFZCSW0waVZLY3c2Q2NVQzltWlhmNGhrMCsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  server.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQzBOMzg5TzNQb2hhNFAKOFVqRFJtQ1QrazNPdU1JMTh3SzBScnJHcUh3czFLdFZJWnZqQUQzN0xUSm8xc1VwaXhzR2dNWnhlb1JLbGlTdwpqQnpvT0l2MWVNcmRvNTg1Q1NJTjdodVhmT1UyQXgyeDlpZDJBMFgzVjdnK3ZNSjhYL1U4RjFDTGhlRGRwMEFZClRQdVhxUGF0RmZOTlpSR2w3VzJxeE8zRjFqb3FILzk3MU1Yc0M4MzgrVWRBWmMvbDNvQUljZ3pEcml2WkkvQ0kKUGJZajZlbm9TZzQrejNzeFNTNU5XamdoSGtUbXB2TEZ5RFhycENTUy9FalNFeWxjQ2hORTB4WWF3R1dHdjVRYQpnZWNuMzlVY2RmTVBtRGF6VEw4OFBNZHBUQmllYURabDloVW14TXFjd2RvYkdIdkZTTEJ5QmEwVDU5SlVzMklICms3S2VSRTRKNjNaUGZkTFE2UDBJR3VOQnVoZTJWMXZRUWZGUVY3NERFeFp3UTR0MXhvUkN3S1lLTkdhM2owSVUKd0kvbHBZYWtKa05HTHJBLzYwVU5XWCtKNzRVTGs3Qi9LeUd2S0QxdmhzZXZFU0JXdnJnQTZFT2dnYTBmTzVRdAoveERhQk9JZE56M3Nmenp1NmJQcFlJdzhFdEFmL0pMQ0FXcFlqT1V2NlAwUFlhZ1BIdzFjLzRJLzkwZnA5b0NFCmkwampsb1RYcm9Kbll5cUlid2ZQcGdJK0tqNG5iSHErbUorSjRtQmo3ZUovU09SQ0E4UHAvUDdEc1hSSHBXN3QKZGl0dUIvSUdWSVYvQStiLzBrVmU2aVY4c1doZ3BlYUtRNm1xUWIybTMveVhSUS83azlXVndHaUYxOE1ZWXc1agpMUDBhcDErVUdpclJYdlYyTjZmSlRQb3BuUng1N3dJREFRQUJBb0lDQUZGRytqNnVjbzc2dzA3elhnS2IyZkRECklaWks0MlFiYml2Si9uQ2NDaXpaMlUreXNiQ0dLbTMrcTA1M0ZrS3ZOd2dPeWZEaDlZb0IveGdVaVBEK2w3aWsKdXJHTkdzRkphaTlvSk0rRWg0ZDlqa1gxbzBScEk0UHk3dWgwank0eXhOSk9IWWhmWDlQM20wT2FiSm13blZmZwpuM05YVXNkSHRuOGZBN0dHOVlLTUhkaEdWT0VwVGNSNjFIU3B0a0tRdjZPUGRFeElZQVExWGtURHVFS29PMU1GCkd6bWVyNHZCMm4wT1pHUWpWNlhDdzVrSnU2L0R2cTcvMHdQVG1vS2xGSjJrcWNKMDVSVUprQTBJYXkwam1PU1cKR1lIOS95V01SbTh2Wml3S0lzeEdhY3BBV3JlNlp6cWRmdlZiYkc3RVlyZDU4ZDRaWGxYTzlUWS9tWDRoaGlQWApGaVBWK21MUEYzTFVSc0VEbDl3WUt2Rk1EenlWOCtzUnNqNlJQclN4ODAwZjA3NXFlVURsaExDZ1BLVG5EbFBjCmJEeGVoRXdtVG5Ud0ZFamNKWWVJemJYdGRXaDFkT1Z6UktvMzhpZ2daVXQ0QlpMUzhuMngrTFJGckE1K2hVRVUKTFRqcllVdkoySWdId0t2MXFsOFQ0bFN3MTJwMEw0RHh5UmRPaGZSV2IraS9td3M1VWM4N3g5c3pMWWwwTldHWApFR2MxbERYVkN5SCt6SDc1OUtja3cwcVVkRXdMR29rN0JTQkdhV1ZjWTF0UGF2UnJnM3FVb2JzRkRDNGhzK2RxCmFlVEJ2TDZBS2VhTnFuQTVURkZyakdNVkxiTWxRcEhNRkN3OFkzbk0vaERIZm9ZRHhjNmJlUS9YNkRYMm91T1kKUlh0N0EzVGNEbXdiandsbWdxWVpBb0lCQVFEajJHTENobUpyOFMyMFU5OVFYUDloNTNSNkRtQWE2UFU0TFltWQp0b0lkNVVnczZybUNwb1VLTlR0WmxVZWFhbjhueE93eC9qeC9iTXo4U2wrVUU2dFZiUlRxOExXcUNvNlFNeExSCldUZEtQQ1h5L3RJcVR5NnR6VFpLcUliakZaQmtRcWE4WDA3SndaUC9obkQrdVA1eUZkbmRDQWliZDNMNnh4QmwKSElaZHFvQUx4Ui9QT3o5Q2dHQ3NsZkRNVVlDaUJzRlRFNWMwcWljUUpFSFVpSkt5dHVIVVNZZHhPeW1wR2k1dQpZS29pTDlWYVc4UStMb0o2eWx6eEZ2Tndab1d2emRQTkFHODEyY25UcFAwR1ZtN1gzR0JvbTJHZHNtS3F4WUNQCm1VQWpNSlhPbCtJcUdrb29RSUdUV1FybFpxOG1XMFh1QVFuL2JvK3NKUU5QWm1HdEFvSUJBUURLZkhEckZ0MGQKUGdDWldtanFJaGtNQ0xaMGlPcXF0RW5hMUVBWlZGZDVRdTAyTVFsYnlubWF1NXNLd3JESjlVcDdhZVUrbDhnSQozaHF6VHBxaEJobkgvZnJ6MUx1eVBiS0wxcWdjRng0TUQzUFg2Q1pHTk5HNWVEd2lRNE5ZRnZ6NWhYcWJWN2l0Cm0yQTJORDcyZThBeDkzTVh2eEpOOXpNRDVmbGdteUpnVTRmMnNhMUw5V3BQZUFkdlR5Z3BuVFUvc0RHcUsxWC8KeklXZTRSUm1nK3FtYmZDalZEODdUNVFBdkp5cElXdVNlbFZZWmlVOE5JODdiUFFyVW1udHhHV3BNNGdXYzRxcgprdXlVS0w1N1ZWY01FSCtBYjJxcGx2UkxNcGwyYTlONGkzTjlQYW1iMWd4dXB6a3pPdUYwd2piSVJTRzN5NmZKCmdTd3JPcXNUVTFXTEFvSUJBUUNKV21VUEI1eEZuanNEUHB5ZEFiTWkvamtGYTYwY0M5dm9aZXRSR0pVUUdLeU8KQjJLV0ZIU1hWc2ZVbFYxNUJVSnFZeGhRZXdkVmVlMkpHZnpNYzU4Ui9KUmpuWUNtWlg3VUJ6WU01aytpZk9nVAp1UEpSZHpLWXErRlMySTJZVCtPZnpWNWVxTVlDY3FRWm9wNXpzR29UdElDRjh0WGRnd0RabFMrWkJMMHJzaUZHCjl5clo3c21QK1h4T0RvWC9aaEs1bW9EbzZDSjdLU2dyWHZBZ2c4U0w0QnY3c2Vmb3B0WFNqMm4yT0dmWC9DWU8KTnN2ekFHN0FQMFlRUU5tNHBOVnF5aFlvdTE1UGhGOWJLMWN0ZnVXTFU5cjZ0TkVBRkEzUERRa1hpRGRWLzNBUAoveGZrY2J6S3p6aE43NXZWOXpVWFZtYXR1QXFpNWEvUEF2RWY2SVJ4QW9JQkFINGs0RVBVenBOMUdQSndmSVBBCkVsS0k2d0hXZWpzMmJmeEIxbHp4U2oxbEVGcCtXaEl4SldqY0QwNjQwMkk5eWRUd3Q3d3kybytMcnA2ZURYN2IKU2h4cGdYbDl3aURjaHVyUEk1TzhZeCtvVU1iay9WTW5mTEJLMDB1Vk83SVpRQ2hDbTR0REx1NFlxZXVheU03TgpjWUt2WWFnZGhNM0ZmcWFqRXFTNGdNWDV3KzVQNm1JejFiTUVWNzFrVnVUMTUwSnlCYjY1bUszdlFCOG1vWXJzCkM3YjdMcnJSdFVMQjVMWkF5bWdqUmR6UEVYUXN6bTJmWU12b3FJU0VwekZVOVBCZ0JodldoMEUwR3VhQ0s0aXkKTmJSeVlyd2tyUkpSMUljMFVwNlB0Z0tXL2ErOFJubXE4N3ZMdWJyTXA4QVJiZ2Q5NmUrU2xFallqQ2V5T1BtbApKTmtDZ2dFQWVZZmpHZDFUTFB5Yks0OHdLSGlCaVp3RU15UWF3SzlXdUJGdTB5eEp5a0c3anNKdTF5djgyMFQ0CnBRREcwb0s2Zko1U2t4NU9hWnlNQlFJNGpwdnBjYUpHS2dDZWRkUXZoWUNUV09ncW9iMWxJejFzRitWbXlzNzgKTUxpS1ZDZHM1VnRvend4eG82aHBVcXQ0T1ZSV3prUHJaTFJmK05LZ2wwY01FYWo3K2tlSUMwSUZRL0IrYU9FZgpwNGxOaXhqMzBMcGdRRWlCUXdqVTFHMWF4Nlk4cDBzUDdkNWRQano3OGpNbDE0MU52Qmw2amJLa1NVR3g4Wm1oCnQvT215YlpCbU9KZTIwaGlPTW0xUlVoVmZmYmxraDhsYmNIalY5cHNtWXV2c21yREthcUx4SnlkUmRwc2RYa3IKM1NWRXFqRTF5d1dDbjhybTFKSkdaUjM5RVR1TkpBPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
