apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-service
  namespace: defectdojo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap-service
  template:
    metadata:
      labels:
        app: zap-service
    spec:
      containers:
        - name: zap
          image: owasp/zap2docker-live
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              zap-baseline.py -t http://example.com -r /zap/wrk/report.html && \
              echo "=== ZAP REPORT START ===" && \
              cat /zap/wrk/report.html && \
              echo "=== ZAP REPORT END ==="
          env:
            - name: DEFECTDOJO_URL
              value: "http://10.102.74.156:30080"
            - name: DEFECTDOJO_API_KEY
              value: "your-api-key"
---
apiVersion: v1
kind: Service
metadata:
  name: zap-service
  namespace: defectdojo
spec:
  selector:
    app: zap-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
